[project]
name = "ishop"
version = "0.1.0"
description = "iShop Api"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.40",
]

[tool.uv]
fastapi-app = "src.main:app"
fastapi-host = "127.0.0.1"
fastapi-port = 8080

[tool.uv.env]
PYTHONPATH = "."