from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from .models import User
from .repository_interface import UserRepositoryInterface


class UserRepository(UserRepositoryInterface):
    def __init__(self, session: AsyncSession):
        self.session = session

    async def insert(self, user: User) -> User:
        """
        Asynchronously inserts a new User record into the database.

        Args:
            user (User): The User instance to be added to the database.

        Returns:
            User: The newly inserted User instance with updated fields (e.g., autogenerated IDs).

        Raises:
            SQLAlchemyError: If the database operation fails.
        """
        self.session.add(user)
        await self.session.commit()
        await self.session.refresh(user)
        return user

    async def email_exists(self, email: str) -> bool:
        """
        Check if a user with the given email exists in the database.

        Args:
            email (str): The email address to check for existence.

        Returns:
            bool: True if a user with the specified email exists, False otherwise.
        """
        query = select(1).where(User.email == email).limit(1)
        result = await self.session.execute(query)
        return result.scalar_one_or_none() is not None

    async def get_by_email(self, email: str) -> User | None:
        """
        Asynchronously retrieves a User instance from the database by email address.

        Args:
            email (str): The email address of the user to retrieve.

        Returns:
            User | None: The User object if found, otherwise None.
        """
        query = select(User).where(User.email == email)
        result = await self.session.execute(query)
        return result.scalar_one_or_none()

    async def get_by_id(self, user_id: int) -> User | None:
        """
        Asynchronously retrieves a User instance by its unique ID.

        Args:
            user_id (int): The unique identifier of the user to retrieve.

        Returns:
            User | None: The User instance if found, otherwise None.
        """
        query = select(User).where(User.id == int(user_id))
        result = await self.session.execute(query)
        return result.scalar_one_or_none()

    async def delete_by_id(self, user_id: int) -> User | None:
        """
        Delete a user by their ID.

        Args:
            user_id (int): The ID of the user to delete.

        Returns:
            User | None: The deleted User object if found and deleted, otherwise None.
        """

        user = await self.session.get(User, user_id)

        if not user:
            return None

        await self.session.delete(user)
        await self.session.commit()
        return user
